### ISSUE TITLE
Moderação do input

### ISSUE THREAD

**Issue by fbraz3** [InternetSemLimites/PublicAPI#3]
Acredito que precisamos de alguma fila de moderação, ou algum sistema de upvote/downvote

Um exemplo: No Rio Grande do Sul foi cadastrado uma empresa chamada blue, cujo escolhendo algumas cidades ele simplesmente direciona pro site da net (tentei com pelotas e aconteceu isto) e a fonte é uma screenshot de uma resposta de ticket de suporte hospedada em site de image aonde até mesmo o protocolo do atendimento está borrado!

Edit: um captcha de repente seria bem-vindo no formulário

**Comment by cuducos** [comment]
Esses sistemas de up/down vote são um pouco mais complicados de
implementar. Vou propor uma sugestão mais simples de implementar, sejam
sinceros e vejam se ajuda, se resolve, se atrapalha…

Pensei em mudar o campo de "publicado" para 3 possibilidades diferentes:
"aguardando moderação" (entre usuário enviar e moderadores chegarem a uma
decisão), "publicado", "negado" (moderadores olharam e decidiram não
publicar).

Pensei em colocar um campo de texto livre para a gente (moderadores)
colocar ali argumentos pró e contra publicação. E, claro, esse campo só
moderadores teriam acesso…

O que acham?

**Comment by cuducos** [comment]
Bom, tá feito, tá implementado no CMS.
Se ficou ruim, só falar que dou um Ctrl Z ; )

**Comment by cuducos** [comment]
Usando esse novo modelo por uns dias, vi que tem **muito** caso em uma dessas duas categorias de _recusado_:
- Provedor repetido (usuário enviou, mas o provedor, com todos os dados enviados, já está cadastrado)
- Fonte não oferece informações suficientes (por exemplo, página dos planos _atuais_ que não dizem nada sobre o compromisso de continuar sem franquia mais para frente)

Acho que, quando tiver tempo, vou criar uma lista de opções pré-definidas para _recusar_ a publicação de um provedor (e deixar a caixa comentário em texto mesmo assim, caso seja um motivo diferente).

Alguém teria algum outro motivo para incluir nessa lista pré-definida? cc @jlcarvalho

**Comment by cuducos** [comment]
Estou mandando para o servidor mais um update. Agora, para moderar, temos algumas razões pré-definidas:
- Provedor repetido (já cadastrado)
- Fonte não encontrada (404 por exemplo)
- Fonte com informações imprecisas ou erradas (por exemplo, descrição dos planos atuais sem considerações sobre adesão ou não de franquia num futuro próximo)
- Fonte não acessível (ex.: requer login de Facebook)
- Fonte é comunicação privada (ex.: chat ou suporte)
- Outros (com caixa de texto para deixar registrado)

Assim fica mais fácil moderar.

@jlcarvalho e @fbraz3: vocês estão usando o sistema? Deixei uns 8 provedores marcados como _Em discussão_. Quando puderem, verifiquem lá.

**Comment by cuducos** [comment]
Fechando esse tópico por motivos de _monólogo_… mas se alguém mais quiser fazer parte da moderação, só (re)abrir e tocamos ; )
