### ISSUE TITLE
Migrar o formulário de adição de Provedor para o front

### ISSUE THREAD

**Issue by leomeloxp** [InternetSemLimites/PublicAPI#5]
Baseado [nessa issue](https://github.com/InternetSemLimites/InternetSemLimites/issues/41) e potencialmente outras funções, estava pensando em sugerir que o formulário para adicionar provedor da API seja transferido para o site, para que possamos ter um design mais consistente e uma experiência mais fluida. Mas para isso vamos precisar implementar um entry point que receberá um POST com dados que imitariam o que está implementado no momento e limitar o acesso AJAX para somento o domínio do site (InternetSemLimites.github.io). Se vocês estiverem a fim, quando o site estiver pronto para implementar essas informações extras, podemos tentar _casar_ o release dessas funcionalidades no front e backend. 👍🏼

**Comment by cuducos** [comment]
Apoiadíssimo!

O `/new/` já recebe e processa o `POST`—  justamente pensando nisso.

Só preciso desativar o CSRF quando implementarmos o formulário em outro servidor. Para manter a segurança (evitar bots etc.) seria bom ter algum captcha ou algo assim no .github.io, né?

**Comment by cuducos** [comment]
Estou pensando aqui como o design, a UI/UX pode nos ajudar a diminuir o volume de provedores enviados sem _fontes_ do jeito que esperamos.

**Não** acredito que o texto que temos, diagramado como está resolva, mas acho acho ele explica o que estamos buscando:

> Link (redes sociais, nóticia etc.) no qual a empresa se manifestou publicamente afirmando que não irá adotar os limites de franquia.
> 
> Isso é diferente de um link dizendo que ela não adota, hoje, essas medidas. Ou seja, não utilize descrição dos planos ou contratos atuais. Estamos buscando afirmações de compromisso em não adotar franquias no futuro.
> De preferência salve o link no [archive.is](http:/archive.is) e já coloque aqui o link que eles fornecerem.

Acho que podemos, no site, fazer uma espécie de _check list_ antes do formulário para convidar o usuário refletir sobre esses pontos e — talvez — fazê-los perceber que a empresa não ter nada nos planos/contratos _hoje_ não diz nada sobre o compromisso dela para o futuro.

Digo isso pois é imenso o número de provedores que recebemos com o link do site do provedor como _fonte_ (e não é nada de divulgação _anti-franquia_, é só o descritivo dos planos que **hoje** são sem franquia).

(E sempre repito: se alguém mais quiser ajudar na moderação desses provedores que recebemos, só falar comigo em PVT que crio um acesso ao CMS.)

**Comment by cuducos** [comment]
Com o c786ba7 qualquer site/domínio/IP pode usar o endpoint `/api/provider/new/` via `POST` para criar novos provedores.
