### ISSUE TITLE
md source files offline

### ISSUE THREAD

**Issue by fbraz3** [InternetSemLimites/PublicAPI#6]
tanto o HALL_OF_SHAME.md quanto o README.md estão offline.

o sync tinha excluido o hall of shame, em função disto, fiz rollback do md e implementei validação de http status no sync.

**Comment by cuducos** [comment]
Visse meu comentário na #2, né? É só atualizar as URLs (ou copiar o shell script aqui do repo pro teu servidor).

**Comment by fbraz3** [comment]
aí que tá. as urls do bash novo estão offline.

> - URL=https://internetsemlimites.herokuapp.com/api/HALL_OF_SHAME.md
>   ++ curl --write-out '%{http_code}' --insecure --connect-timeout 5 --silent --output /dev/null https://internetsemlimites.herokuapp.com/api/HALL_OF_SHAME.md
> - STATUS=404
> - '[' 404 '!=' 200 ']'
> - echo 'invalid http status'
>   invalid http status
> - exit 0
> - URL=https://internetsemlimites.herokuapp.com/api/README.md
>   ++ curl --write-out '%{http_code}' --insecure --connect-timeout 5 --silent --output /dev/null https://internetsemlimites.herokuapp.com/api/README.md
> - STATUS=404
> - '[' 404 '!=' 200 ']'
> - echo 'invalid http status'
>   invalid http status
> - exit 0

**Comment by cuducos** [comment]
Putz! Erro meu! Estou na rua, teclando do celular, mas se quiser ir
corrigindo: ao invés de `/api/` é `/markdown/` nas URLs! Mal aí, falha
minha.
